"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { themeFromType } from "@/lib/competitionThemes";

type Message = { id:string; league_id:string; league_competition_id:string|null; user_id:string|null; message_type:string; content:string|null; mentions_data:any; created_at:string; team_name?:string|null; competition_name?:string|null; competition_type?:string|null };
type Competition = { id:string; name:string; competition_type:string|null };

type Props={leagueId:string;currentUserId:string;currentTeamName:string;activeLeagueCompetitionId?:string|null;competitions?:Competition[]};

export default function ChatPage({leagueId,currentUserId,currentTeamName,activeLeagueCompetitionId,competitions=[]}:Props){
 const[messages,setMessages]=useState<Message[]>([]); const[input,setInput]=useState(""); const[loading,setLoading]=useState(true); const[sending,setSending]=useState(false); const endRef=useRef<HTMLDivElement>(null);
 const compMap=useMemo(()=>new Map(competitions.map(c=>[c.id,c])),[competitions]);
 useEffect(()=>{async function load(){setLoading(true); const {data}=await supabase.rpc("get_chat_messages",{p_league_id:leagueId,p_limit:200}); if(data){setMessages(data as Message[])}else{const res=await supabase.from("messages").select("*").eq("league_id",leagueId).order("created_at",{ascending:true}).limit(200); setMessages((res.data??[]) as Message[])} setLoading(false); setTimeout(()=>endRef.current?.scrollIntoView({behavior:"auto"}),50)} load();},[leagueId]);
 useEffect(()=>{const ch=supabase.channel(`chat:${leagueId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`league_id=eq.${leagueId}`},(payload)=>{setMessages(p=>[...p,payload.new as Message]);setTimeout(()=>endRef.current?.scrollIntoView({behavior:"smooth"}),80)}).subscribe(); return()=>{supabase.removeChannel(ch)}},[leagueId]);
 async function send(){const text=input.trim(); if(!text||sending)return; setSending(true); setInput(""); const {error}=await supabase.rpc("send_chat_message",{p_league_id:leagueId,p_league_competition_id:activeLeagueCompetitionId??null,p_content:text,p_message_type:"text",p_mentions_data:null}); if(error){await supabase.from("messages").insert({league_id:leagueId,league_competition_id:activeLeagueCompetitionId,user_id:currentUserId,content:text,message_type:"text"});} setSending(false)}
 return <div style={s.wrap}><div style={s.header}><div style={s.icon}>💬</div><div><b>Chat Lega</b><small>Unica per tutte le competizioni</small></div></div><div style={s.messages}>{loading?<div style={s.center}>Caricamento...</div>:messages.length===0?<div style={s.center}>Nessun messaggio. Inizia la conversazione.</div>:messages.map(m=>{const own=m.user_id===currentUserId; const comp=m.league_competition_id?compMap.get(m.league_competition_id):null; const type=m.competition_type??comp?.competition_type??null; const theme=themeFromType(type); return <div key={m.id} style={{...s.bubbleWrap,justifyContent:own?"flex-end":"flex-start"}}><div style={{...s.bubble,background:own?theme.primary:"white",color:own?"white":"#111827"}}>{m.league_competition_id&&<div style={{...s.badge,background:own?"rgba(255,255,255,.18)":theme.badgeBg,color:own?"white":theme.badgeText}}>{m.competition_name??comp?.name??"Competizione"}</div>}<div>{renderMessage(m,currentTeamName)}</div><small style={{opacity:.65}}>{new Date(m.created_at).toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"})}</small></div></div>})}<div ref={endRef}/></div><div style={s.inputArea}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} placeholder="Scrivi in chat..." style={s.textarea}/><button onClick={send} disabled={sending||!input.trim()} style={s.send}>➤</button></div></div>
}
function renderMessage(m:Message,currentTeamName:string){if(m.message_type==="lineup_notification")return <span><b>{m.team_name??currentTeamName}</b> ha caricato la formazione</span>; if(m.message_type==="nyx")return <span>🎙 {m.content}</span>; if(m.message_type==="matchday")return <span>⚽ {m.content??"Nuova giornata"}</span>; return m.content??"";}
const s:Record<string,React.CSSProperties>={wrap:{display:"flex",flexDirection:"column",height:"100%",background:"#f9fafb"},header:{background:"white",borderBottom:"1px solid #e5e7eb",padding:"12px 16px",display:"flex",gap:10,alignItems:"center"},icon:{width:38,height:38,borderRadius:12,background:"linear-gradient(135deg,#16a34a,#f97316)",display:"grid",placeItems:"center"},messages:{flex:1,overflowY:"auto",padding:12,display:"flex",flexDirection:"column",gap:8},center:{margin:"auto",color:"#9ca3af",fontWeight:800,textAlign:"center"},bubbleWrap:{display:"flex"},bubble:{maxWidth:"82%",borderRadius:16,padding:"9px 12px",boxShadow:"0 1px 4px rgba(0,0,0,.08)",display:"grid",gap:4,fontWeight:600,whiteSpace:"pre-wrap"},badge:{display:"inline-flex",justifySelf:"start",borderRadius:999,padding:"2px 8px",fontSize:10,fontWeight:900},inputArea:{background:"white",borderTop:"1px solid #e5e7eb",padding:10,display:"flex",gap:8},textarea:{flex:1,border:"1px solid #e5e7eb",borderRadius:18,padding:"10px 12px",resize:"none",fontFamily:"inherit"},send:{width:42,height:42,borderRadius:"50%",border:0,background:"#16a34a",color:"white",fontWeight:900}};
